tryber/sd-09-project-trivia-react-redux

- src/App.js
> Initial Commit

- package-lock.json
- package.json
- src/App.js
> [GRUPO-25] Setup Inicial

- package-lock.json
- package.json
- src/App.js
- src/actions/index.js
- src/index.js
- src/pages/Home.js
- src/reducers/index.js
- src/reducers/loginReducer.js
- src/store/index.js
> Configurações iniciais do Redux e Requisito 1

- package.json
> "[GROUP-3] First Commit"

- package-lock.json
- package.json
- src/App.js
Fizemos a estrutura inicial da aplicação, criamos as pastas para organizar o código
> [GROUP 18] - Estrutura inicial

- package-lock.json
- package.json
- src/App.js
- src/index.js
- src/pages/Login.jsx
- src/reducers/index.js
- src/store/index.js
> [GRUPO-25] Requisito 1

- package-lock.json
- package.json
- src/App.js
- src/Pages/Login.js
- src/index.js
- src/redux/reducers/index.js
- src/redux/store/index.js
Implementation of requirement 01
> [GROUP-7][Feature] Requisito 01

- src/App.js
- src/pages/Login/Login.js
- src/pages/Settings/Settings.css
- src/pages/Settings/Settings.js
> [Grupo 06] - Requirement 03

- src/App.js
- src/actions/actionsTypes.js
- src/actions/index.js
- src/pages/Login.jsx
- src/pages/Play.jsx
- src/services/tokenGenerator.js
> [GRUPO 25] Requisito 2

- package-lock.json
- package.json
- src/App.js
- src/actions/index.js
- src/index.js
- src/pages/Game.jsx
- src/pages/Login.js
- src/reducers/gameToken.js
- src/reducers/index.js
- src/services/index.js
- src/store/index.js
> O botão "Jogar" deve fazer requisição para a API para obter o token e redirecionar a pessoa para tela de jogo.
<br>
**Observações técnicas:**
> [GRUPO 33] Projeto Trivia - Requisito 02

- src/App.css
- src/App.js
- src/index.css
- src/index.js
- src/pages/login.js
- src/pages/settings.js
- src/pages/trivia.js
Pessoal, criei a Tela de login com validação de email.
As rotas para as paginas de configuração e a pagina do jogo também estão criadas, assim como os respectivos arquivos (Sem implementação interna).
No login, ainda falta implementar a regra de negócio para fazer a requisição a partir do email, assim como salvar o nome e email.
> Main group 20 tela de login

- package-lock.json
- src/css/header.css
- src/pages/header.js
- src/pages/trivia.js
criei uma pasta css, onde poderemos colocar os arquivos css de cada componente
> componente header pronto

- src/App.js
- src/components/Login.js
> First Commit 

- src/components/Feedback.js
- src/components/GameScreen.js
Estrutura do requisito 4 e 12 feitas.
> [Grupo 3] adiciona header no componente feedback e gameScreen

- src/App.js
- src/index.js
- src/pages/Login.js
> [Group-15][Req-1]

- package-lock.json
- package.json
- src/App.js
- src/actions/action.js
- src/pages/Game.jsx
- src/pages/Header.jsx
- src/pages/Login.jsx
- src/pages/Settings.jsx
- src/reducers/index.js
- src/services/funcoes.js
Aí, galera, depois de 1 hora para entender que estava buscando uma chave name, que na verdade era userName, está aí o requisito 4. Faltou implementar a fetch da api do gravatar. Mas o requisito está cumprido.
> Group 23/requisito 4

- package-lock.json
- package.json
- src/App.js
- src/actions/action.js
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/pages/Settings.jsx
- src/reducers/index.js
- src/services/funcoes.js
Galera, requisito 3 OK. Confiram por favor.
> Group 23/requisito 3

- src/App.js
- src/components/Game.js
- src/components/Login.js
- src/services/api.js
> Requisito 2

- package-lock.json
- package.json
- src/App.js
- src/actions/index.js
- src/index.js
- src/pages/Login.js
- src/reducers/index.js
- src/reducers/user.js
- src/services/api.js
- src/store/index.js
Criada tela de login e criado o setup do redux.
> feat/req1 and feat/req2

- src/App.js
- src/pages/Config.jsx
- src/pages/Login.jsx
> Adiciona requisito 3

- package-lock.json
- package.json
Este *pull request* cria a estrutura inicial do projeto, com diretórios e arquivos.
> [Grupo 31] Requisito 0 - Cria estrutura inicial da aplicação

- package-lock.json
- src/App.js
- src/helpers/fetchToken.js
- src/pages/Game.js
- src/pages/Login.js
- src/pages/Settings.js
- src/redux/actions/actionstype.js
- src/redux/actions/index.js
- src/redux/reducers/index.js
- src/redux/reducers/tokenReducer.js
- src/redux/reducers/userRegisterReducer.js
> [GRUPO 14] - Requisitos 2 e 3

- src/App.js
- src/index.js
- src/pages/Login.jsx
> [GROUP 18] - Requisito 1

- src/App.js
- src/Pages/Login.js
- src/redux/actions/index.js
- src/redux/actions/typeActions.js
- src/services/fetchApi.js
> [GROUP-7][Feature 2] Requisito 2

- src/pages/Login.js
- src/services/api.js
Implementação das requisições da API das questões de TRIVIA  realizando o armazenamento do token no localstore da aplicação.
> Main group 26 /feat/requisito 02

- src/App.js
- src/pages/GameSettings.js
- src/pages/Login.js
Implementada rota e botões para a pagina de configurações do jogo.
> Main group 26 /feat/ requisito 03

- src/actions/index.js
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/reducers/gameToken.js
- src/reducers/index.js
- src/reducers/player.js
> O header deve conter as informações sobre a pessoa jogadora, como a imagem do Gravatar, o nome e o placar.
<br>
**Observações técnicas:**
> [GRUPO 33] Projeto Trivia - Requisito 04

- package-lock.json
- package.json
- src/pages/Game.js
- src/pages/components/Header.js
> Main group 15 req 4

- src/App.js
- src/pages/Home.js
- src/pages/Login.js
- src/pages/Settings.js
Adiciona o header da tela Home
> Add requirement 4

- package-lock.json
- src/services/Api.js
Criado diretório 'services' e 'Api.js' com as funções para requisição das api's.
> [Group 2][Feat][Req1.3]

- src/App.js
- src/pages/Configuration.jsx
- src/pages/Login.jsx
> [GROUP-18] - Requisito 3

- src/App.js
- src/components/Header.jsx
- src/pages/Feedback.jsx
- src/pages/GamePage.jsx
- src/pages/Login.jsx
> adiciona requisito 15

- src/pages/Feedback/Feedback.js
Obs: adicionados os placeholders para os requerimentos 12 e 13, necessária a conexão depois dos requerimentos 10 e 11
> Grupo 6 - Placeholder para requisitos 12 e 13

- src/App.js
- src/index.js
- src/pages/Game.js
- src/pages/Login.js
- src/reducers/index.js
- src/reducers/loginReducer.js
- src/services/tokenAPI.js
Faz requisição para gerar token ao iniciar jogo e salva no LocalStorage
> [FEAT][REQUISITO 02][Cria botão de iniciar jogo e salva token][V1.4]

- src/App.js
- src/Pages/InfoGames.js
- src/Pages/Login.js
- src/Pages/Settings.js
- src/components/Header.jsx
- src/redux/actions/index.js
- src/redux/reducers/index.js
- src/redux/reducers/user.js
- src/services/fetchApi.js
> [Group-7][Feature] Requisito 3 and 4

- src/pages/components/Questions.js
- src/styles/components/Questions.css
> [Group-15] - Requirement 7

- src/pages/Game.js
- src/pages/components/Questions.js
- src/pages/components/Timer.js
- src/redux/actions/index.js
- src/redux/reducers/index.js
- src/redux/reducers/timer.js
> [Group-15] - Requirement 8

- src/pages/Feedback.jsx
- src/pages/GamePage.jsx
Requisito 16 - Adiciona botão que ao ser clicado redireciona para tela de ranking
> [Gurpo 9]Adiciona requisito 16

- src/Redux/actions/index.js
- src/Redux/reducers/index.js
- src/Redux/reducers/score.js
- src/components/FeedbackHeader.jsx
Cria o estado currentScore para aparecer os valores atualizados no header de feedback.
> [GROUP2][FEAT][REQ12]

- src/components/Timer.js
> Main group 26 /feat/ requisito 08

- src/App.js
- src/pages/Play.jsx
- src/styles/Play.css
> [GRUPO 25] Adiciona os requisitos 7 e 8

- src/App.js
- src/pages/Login.jsx
- src/pages/Play.jsx
- src/styles/Play.css
> [GRUPO 25] Requisito 9

- src/CSS-Components/Choices.css
- src/compenents/cardQuestion.js
> [Grupo14] Requisito10

- src/Components/TriviaCardsBA.js
- src/Components/TriviaCardsMA.js
- src/Pages/Trivia.js
- src/Pages/answers.css
não consegui ainda resolver o problema de correct anwers no lint
> Grupo 01 trivia feat next btn

- src/actions/index.js
- src/components/CardQuestion.jsx
- src/components/Loading.jsx
- src/components/PlayerHeaderInfo.jsx
- src/pages/Game.jsx
- src/reducers/gameQuestions.js
> A pergunta deve ter apenas uma alternativa correta.
<br>
**Observações técnicas:**
> [GRUPO 33] Projeto Trivia - Requisito 06

- package-lock.json
- package.json
- src/actions/trivia.js
- src/actions/types.js
- src/pages/Login.js
- src/reducers/index.js
- src/reducers/trivia.js
- src/services/api.js
- src/services/index.js
- `services/api.js`  : Adiciona função `getTriviaQuestions` para requisição à API da Trivia;
- `actions/trivia.js` & `reducers/trivia.js` : Adiciona *actions* e _reducer_ para armazenar as questões requisitadas da Trivia;
- `store/index.js` : Implementa chave `trivia` na *store*; 
- `pages/Login.js` : Adiciona _action_ da Trívia nas props e implementa funcionalidade no botão _Jogar_.
> [Grupo 31] (feat) Adiciona requisito 2

- src/actions/actionsTypes.js
- src/actions/index.js
- src/components/Header.jsx
- src/components/Timer.jsx
- src/pages/FeedBack.jsx
- src/pages/Play.jsx
- src/reducers/triviaReducer.js
> [GRUPO 25] Requisito 13

- src/components/FeedbackHeader.jsx
adiciona alt na foto do profile
> [GROUP2][FIX][Req7]

- src/App.js
- src/actions/index.js
- src/components/Answers.jsx
- src/components/Header.jsx
- src/pages/Feedback.jsx
- src/pages/Game/game.css
- src/pages/Login.jsx
- src/reducers/index.js
- src/reducers/playerReducer.js
> [FEAT][Requisitos 8 ao 12]

- src/App.js
- src/components/FeedbackHeader.jsx
- src/components/LoginForm.jsx
- src/pages/Settings.jsx
>  [Group 2][Feat][Req3]

- src/components/FeedbackHeader.jsx
> [Group2][Fix][Req4]

- package-lock.json
- package.json
- src/pages/Game.js
Em `pages/Game.js`, implementa: 
- acesso à store do React Redux,
- renderização do componente `Header`,
- propTypes.
> [Grupo 31] (feat) Merge requisitos 2 a 5

- README.md
- package.json
Como o erro desse conflito foi da Trybe, estou resolvendo manualmente.
> Solve conflict

- src/components/question.js
- src/pages/trivia.js
- src/redux/actions/index.js
- src/redux/reducers/actionsReducer.js
To colocando no git pra vcs verem as alterações que fiz, mas não fechem essa pr ainda pois vou contiuar nesse requisito
> Requisito 8

- cypress/integration/project.spec.js
- package-lock.json
- src/pages/Login.js
- src/pages/components/Header.js
- src/pages/components/Questions.js
- src/pages/components/Timer.js
- src/redux/actions/index.js
- src/redux/reducers/index.js
- src/redux/reducers/player.js
- src/redux/reducers/timer.js
> [Group-15] - Requirement 9

- src/components/Questions.css
- src/components/Questions.js
- src/pages/Login.js
- src/reducers/game.js
Corrige requisito 5 e implementa o 7
> Main group 5 feat req7

- src/components/Questions.js
- src/pages/Login.js
> main-group-5 adiciona requisito 8

- src/App.js
- src/actions/action.js
- src/common/components/QuestionCard.css
- src/common/components/QuestionCard.jsx
- src/common/components/Timer.jsx
- src/pages/Feedback.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/reducers/index.js
Requisito 8 feito.
Requisito 9 e 10 quase prontos
> Group 23/requisito 9

- src/actions/action.js
- src/common/components/QuestionCard.css
- src/common/components/QuestionCard.jsx
- src/common/components/Timer.jsx
- src/pages/Game.jsx
- src/reducers/index.js
> Group 23/requisito 8

- src/pages/Login.jsx
- src/pages/Play.jsx
> [GRUPO-25]Tentando consertar o requisito 3

- src/App.js
- src/components/Question.js
- src/pages/Game.js
- src/pages/Login.js
Adiciona requisitos 6 e 7,  adaptando `Game.js` aos problemas encontrados com o Cypress, além das seguintes alterações:
- refatoração da página `Game.js`;
- implantação do componente `Question.js`, para o qual a renderização da questão é transferida visando dar uma ordem aleatória às alternativas de respostas que é mantida após a questão ser respondida.
> [Grupo 31] Adiciona requisitos 6 e 7

- src/pages/Feedback.jsx
- src/pages/Ranking.jsx
- src/pages/ScreenGame.jsx
Observações técnicas
- Deve-se mostrar uma lista com a imagem de perfil vinda do Gravatar, nome e pontuação das pessoas que jogaram em ordem decrescente (da maior pontuação para a menor)
- Os elementos com os nomes das pessoas que jogaram devem possuir o atributo `data-testid` com o `valor player-name-${index}`, onde `${index}` é iniciado em zero
- Os elementos com as pontuações das pessoas que jogaram devem possuir o atributo `data-testid` com o valor `player-score-${index},` onde` ${index}` é iniciado em zero
- O ranking deve ser armazenado no navegador através do `localStorage`.
> [Group 30] [FEAT] [Requisito 17]

- src/pages/feedback.js
Coloquei as divs com os data-testid, e estou puxando o score do redux. Falta a lógica pra sobrescrever os pontos lá no state global.
> estrutura pronta, faltando a logica dos pontos

- src/Components/FeedHeader.js
- src/Components/TriviaCardsMA.js
- src/Pages/Feedback.js
- src/Pages/Ranking.js
**ESTE É UM PR TRISTE** 😭
❌ _NÃO SE ASSUSTEM COM A QUANTIDADE DE TESTES FALHANDO_ ❌
O requisito 17 está **pronto**, portanto estão todos PRONTOS!!! 🚀 
PORÉM, isso fez com que um dos testes (que tá em **VARIOS** requisitos) quebrasse.
Ele testa a quantidade de keys do localStorage, e só pode ter **3** keys (ver: [Observações Técnicas](https://github.com/tryber/sd-09-project-trivia-react-redux#observa%C3%A7%C3%B5es-t%C3%A9cnicas)).
Assim sendo, vamos ter que _refatorar_ a parte do `<timer.js>` (talvez salvar ele no estado global?) 🤓🤓
VQV
> [Grupo1] - feat/req17

- src/App.css
- src/components/GoHome.jsx
- src/components/Header.jsx
- src/components/Timer.jsx
- src/index.css
- src/pages/Config.jsx
- src/pages/Feedback.jsx
- src/pages/GamePage.jsx
- src/pages/Login.jsx
- src/pages/Ranking.jsx
> Main group 9 css

- src/components/Header.jsx
- src/pages/Login.jsx
- src/pages/Play.jsx
- src/pages/Ranking.jsx
> [GRUPO-25] Requisitos 17 e 18

- src/actions/game.js
- src/components/NextButton.js
- src/components/Questions.js
- src/pages/Feedback.js
- src/reducers/game.js
- Adiciona Redirecionamento para a pagina de feedback apos a quinta questao.
- Corrige a renderização do botão de próxima questão para ficar visível assim que uma pergunta for respondida.
- Adiciona o score ao localStorage (acredito que a logica no redux precise ser alterada pois a pontuacao nao esta sendo marcada corretamente).
- Tentei adicionar o numero de questoes acertadas (para redirecionar a menssagem de feedback correta) ao localStorage porem ainda nao esta funcionado.
> Redireciona para feedback apos a quinta questao

- src/App.js
- src/components/Header.js
- src/pages/Feedback.js
- src/pages/Ranking.js
Adiciona requisitos 12, 16 e 18.
> Main group 5 feat/req12-16-18

- src/components/Header.jsx
- src/pages/Play.jsx
> [GRUPO-25] Fix Req 3

- src/Pages/InfoGames.js
reparo nas respostas das perguntas.
> Main group 7 repair

- src/components/Question.js
- Cria timer para resposta das perguntas.
> [Grupo 31] (Game) Adiciona requisito 8

- src/App.js
- src/pages/Feedback.js
- src/pages/components/Questions.js
- src/pages/components/Timer.js
- src/redux/actions/index.js
- src/redux/reducers/timer.js
> [Group-15] - Requirement 11

- package-lock.json
- src/App.css
- src/pages/Login.js
> Main group 14 req9 - Beto

- src/actions/index.js
- src/actions/score.js
- src/actions/types.js
- src/components/Header.js
- src/components/Question.js
- src/components/Score.js
- src/pages/Login.js
- src/reducers/user.js
- src/services/score.js
- src/services/storage.js
> [Grupo 31] Requisito 9

- package-lock.json
- src/actions/index.jsx
- src/components/Header.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/reducers/user.jsx
- src/store/index.jsx
Corrigido requisito 2
Passando requisitos do 1 ao 4.
Lógica do gravatar feita no componente Header e não mais na page Login.
> Correçao do requisito 2

- src/components/Questions.js
- src/pages/Feedback.js
- src/reducers/game.js
Pequenos ajustes para corrigir o requisito 13
> corrige requisito 13

- src/Pages/InfoGames.js
- src/components/Header.jsx
> feature: calc score

- package-lock.json
- package.json
- src/pages/Question.jsx
- src/pages/css/question.css
> Group 13 - Requisito 7

- src/pages/Game.js
- src/pages/game.css
- src/pages/login.css
Remove bug que fazia as respostas das questões trocarem de ordem ao clicar, remove também outlines no CSS dos botões das respostas e do botão de Login.
> [FIX][Game.js][Conserta bug ao clicar em respostas do jogo e remove outlines no CSS][V1.0]

- src/pages/Rank.js
> Small fix sort the ranking array before render

- src/pages/EndGame.jsx
- src/pages/Question.jsx
correcoes 7-10 e inicio req 11
> Group 13 - Req 11

- src/actions/index.js
- src/components/CardQuestion.jsx
- src/components/FeedbackContent.jsx
- src/pages/Feedback.jsx
- src/reducers/player.js
> A tela de feedback deve conter as informações da pessoa que joga, incluindo o placar com o valor referente ao desempenho no jogo.
<br>
**Observações técnicas:**
<br>
> A tela de feedback deve exibir uma mensagem relacionada ao desempenho da pessoa que jogou.
<br>
**Observações técnicas:**
> [GRUPO 33] Projeto Trivia - Requisitos 12 e 13

- src/pages/Feedback.jsx
- src/pages/Question.jsx
- src/pages/components/CountdownTimer.jsx
- src/pages/css/feedback.css
- src/pages/css/login.css
- src/pages/css/question.css
- src/pages/css/timer.css
Criar uma opção para a pessoa jogadora poder jogar novamente
> Group 13 - Requisito 15

- cypress/integration/project.spec.js
- src/pages/Feedback.js
- src/pages/Login.js
- src/pages/Ranking.js
> [Grupo 31] Requisitos 15-16-18 by Jorge William

- src/App.js
- src/pages/Feedback.js
- src/pages/Ranking.js
- src/pages/components/Header.js
- src/pages/components/Questions.js
- src/pages/components/Timer.js
- src/redux/actions/index.js
- src/redux/reducers/player.js
- src/redux/reducers/timer.js
> [GROUP - 15] - Requirement 17 and 18

- src/App.js
- src/pages/Feedback.js
- src/pages/Ranking.js
- src/pages/components/Questions.js
> [Group-15] - Requirement 16
